{% set name = "pygeogrids" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeogrids-{{ version }}.tar.gz
  sha256: f683735810bf6a1aa6e2ff0c011d866fbec50f20db4f8aa5862a3e422f7bda49

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - python >=3.8
    - pandas
    - numpy
    - netcdf4
    - pyproj
    - pykdtree

test:
  imports:
    - pygeogrids
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/TUW-GEO/pygeogrids
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Creation and handling of Discrete Global Grids or Point collections.

extra:
  recipe-maintainers:
    - cpaulik
    - ocefpaf
