{% set version = "0.4.0" %}

package:
  name: pygeogrids
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygeogrids/pygeogrids-{{ version }}.tar.gz
  sha256: a219d81e6896d33c53a9b02363e34573ac2e2da4d98fac913382e0694aeef502

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pyscaffold >=3.2a0,<3.3a0
  run:
    - python >=3.6
    - netcdf4
    - numpy
    - pykdtree
    - pyproj

test:
  imports:
    - pygeogrids
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/TUW-GEO/pygeogrids
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Creation and handling of Discrete Global Grids or Point collections.

extra:
  recipe-maintainers:
    - cpaulik
    - ocefpaf
