{% set name = "pygeogrids" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygeogrids-{{ version }}.tar.gz
  sha256: 03ce306fb2a32af0c8deec6be05ce2fc118d30e464c1b5091965e41793887f02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - scipy
    - python >={{ python_min }}
    - pandas
    - numpy
    - netcdf4
    - pyproj
    - pykdtree

test:
  imports:
    - pygeogrids
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/TUW-GEO/pygeogrids
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Creation and handling of Discrete Global Grids or Point collections.

extra:
  recipe-maintainers:
    - cpaulik
    - ocefpaf
