travis:
  secure:
    BINSTAR_TOKEN: BwldCmxoNZY9wrnjDwqHw//mPrv+xo700lYnG6jc+BcjU4eZuXFCm9GA7t0snnYkMn705eE55xuahmkkG7uBe0vtyruSMoWA31NRjmiVJ1TIAxoW6tI2elJlulFWk4ckye3AxDdUcnjra3t11Q71P2p82Bm1UagZaluNH3FkSEC0IwVnKDR9jz+V9wPhekpgH7txgMBBCz1h0VhVOuBKvC4druVtAkVDWMFdyFROZo3+pma1wHlBX8yk4Aohdh+A45wSfUxJh/bZNJBhXc/u0PvSH0YOD/PXn9q7bNRUlhmEIZf3v6b9DW8fjy6W7aMahUNKoJwEDVVIyc+RZGuKcQBNoeSEz3TzedlcgOES3KhWGdwccebTRDMetE72mmdTqkkQP2tQKui6ZyyGAGhXKQ71Oa4871cJOwTPOdqjhlP1YxtQUwQ3ajPaiRQVXK6B2PNZ1m/2i/25FJr40UbNWVfYSEvX7mQuUUhXqr4Hg+pPAVZflMc6+j2bgn2p8JphCvmpUw5iywVz4wHB5jvQzgZ8mTtDOOAIjn1lCZLFkCxgFm0ZzD2bqXJ9f2ORXpwKOR0tO743VPszWJpRNz3Rm20rsd3J0eZgTTktg8dcebStCqETD+SBqBoPVRI1rsB1U7kKjMi8YPvSSorx3869P51eDQe9jYpTWN3VPQf4guQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
